version: '3.5'

services:
  emqx:
    image: emqx/emqx:v3.1.2-amd64
    container_name: emqx1
    restart: always
    ports:
      - 1883:1883
      - 18083:18083
    networks: 
      - simpss-net
  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.2
    container_name: zookeeper1
    networks: 
      - simpss-net
    volumes:
      - type: bind
        source: /mnt/kafka-zookeeper/data-zookeeper
        target: /var/lib/zookeeper/data
      - type: bind
        source: /mnt/kafka-zookeeper/logs-zookeeper
        target: /var/lib/zookeeper/log
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
  
  kafka:
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
    image: confluentinc/cp-kafka:5.2.2
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      - simpss-net
    volumes: 
      - type: bind
        source: /mnt/kafka-zookeeper/data-kafka
        target: /var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  cassandra:
    build: ./cassandra-graphite
    container_name: cassandra1
    image: cassandra:3.11
    networks: 
      - simpss-net
    ports:
      - "7000:7000"
      - "9042:9042"
      - "7199:7199"
    # depends_on: 
    #   - graphite
    volumes: 
      - type: bind
        source: /mnt/cassandra/data # on the host machine
        target: /var/lib/cassandra # inside the container

  
  # graphite:
  #   image: graphiteapp/docker-graphite-statsd:latest
  #   container_name: graphite4cassandra
  #   restart: always
  #   ports: 
  #     - 2003-2004:2003-2004
  #     - 2023-2024:2023-2024
  #     - 8080:8080
  #     - 8125:8125
  #     - 8126:8126
  #   networks:
  #     - cassandra-network
  #   volumes: 
  #     - graphite-volume
  
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana4cassandra
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   networks: 
  #     - cassandra-network
  #   volumes: 
  #     - grafana-volume
  #   depends_on: 
  #     - graphite

networks:
  simpss-net:
    driver: bridge

# volumes: 
#   cassandra-volume:
#     external: false
#   kafka-volume:
#     external: false
  # graphite-volume:
  #   external: false
  # grafana-volume:
  #   external: false
