version: '3'

services: 
  cassandra:
    image: cassandra:3
    networks: 
      - cassandra-network
    ports:
      - "7000:7000"
      - "9042:9042"
      - "7199:7199"

networks:
  cassandra-network:
    driver: bridge
